# Generated by Django 5.1.1 on 2024-10-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_remove_dueño_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('pendiente', 'Pendiente'), ('vista', 'Vista'), ('cancelada', 'Cancelada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado_proceso',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('pendiente', 'Pendiente')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='asignacion',
            field=models.CharField(choices=[('mecanico', 'Mecánico'), ('pintor', 'Pintor'), ('electrico', 'Eléctrico'), ('jefe_taller', 'Jefe de Taller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('en_vacaciones', 'En Vacaciones')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('bencina', 'Bencina'), ('diesel', 'Diésel')], max_length=50),
        ),
    ]
