# Generated by Django 5.1.1 on 2024-10-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_alter_cita_estado_cita_alter_notificacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='fase_proceso',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('en_espera', 'En Espera'), ('cancelado', 'Cancelado')], max_length=100),
        ),
    ]
