# Generated by Django 4.2.16 on 2024-10-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_cotizacion_total_estimado_alter_dueño_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('dueño', 'Dueño'), ('administrador', 'Administrador'), ('trabajador', 'Trabajador'), ('supervisor', 'Supervisor')], default='cliente', max_length=20),
        ),
    ]
