# Generated by Django 4.2.16 on 2024-10-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.vehiculo'),
        ),
    ]
