# Generated by Django 5.1.1 on 2024-10-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_alter_proceso_fase_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('trabajador', 'Trabajador'), ('supervisor', 'Supervisor')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='miapp.dueño'),
        ),
    ]
