# Generated by Django 5.1.1 on 2024-10-25 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_perfil_rol_alter_vehiculo_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='rut',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9.', regex='^\\d{7,8}-[0-9kK]{1}$')]),
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='notificaciones',
        ),
        migrations.AddField(
            model_name='proceso',
            name='notificaciones',
            field=models.ManyToManyField(related_name='procesos', to='miapp.notificacion'),
        ),
    ]
